server:
  port: 9092
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_flowable
    username: postgres
    password: 123456

flowable:
  async-executor-activate: false
